const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('app.js', 'utf8').replace(/document\.addEventListener\([\s\S]*?^}\);/m, '');
const context = { console, window: {}, document: {}, localStorage: { getItem() { return null; }, setItem() {} } };
vm.createContext(context);
vm.runInContext(source, context);
context.appState = context.createInitialStore();
const fabric = context.appState.fabrics.find(f => context.getComposition(f.compositionId).components.polyester_coated === 92);
const original = JSON.stringify(context.getComposition(fabric.compositionId));
const style = { name: 'Coating test', yyByFabricId: { [fabric.id]: 2 }, coatingByFabricId: { [fabric.id]: 'uncoated' } };
const calculation = context.calculateStyle(style);
assert.equal(calculation.totals.polyester_uncoated, 0.92);
assert.equal(calculation.totals.polyester_coated, 0);
assert.equal(calculation.totals.polyurethane, 0.08);
assert.equal(calculation.grandTotal, 1);
assert.match(calculation.usedRows[0].compositionLabel, /UNCOATED/);
assert.equal(JSON.stringify(context.getComposition(fabric.compositionId)), original);
assert.equal(context.calculateStyle({ ...style, coatingByFabricId: {} }).totals.polyester_coated, 0.92);
const restored = context.cloneStyle(JSON.parse(JSON.stringify(style)));
assert.equal(context.calculateStyle(restored).totals.polyester_uncoated, 0.92);
assert.equal(context.newDraft(restored).coatingByFabricId[fabric.id], 'uncoated');
const rows = ['coated', 'uncoated'].map(polyesterCoating => ({ fabricName: fabric.name, compositionId: fabric.compositionId, yy: 1, polyesterCoating }));
const imported = context.calculateStyle(context.cloneStyle({ name: 'Imported', rows }));
assert.equal(imported.totals.polyester_coated, 0.46);
assert.equal(imported.totals.polyester_uncoated, 0.46);
assert.equal(imported.totals.polyurethane, 0.08);
assert.equal(context.polyesterRatio({ components: { polyurethane: 100 } }), 0);
assert.equal(context.polyesterRatio({ components: { nylon: 100 } }), 0);
console.log('Polyester coating calculation and persistence tests passed');
